app = "kinjar-api"
primary_region = "iad"

[env]
  PORT = "8080"
  # If you later add a volume mounted at /data, uncomment the next line:
  # DATA_DIR = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  # Deploy/run-time HTTP health check hitting /health
  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

# If/when you create a Fly volume named "data" in IAD, you can mount it:
# [mounts]
#   source = "data"
#   destination = "/data"
