app = "kinjar-api"         # change if different
primary_region = "atl"

[env]
  PORT = "8080"
  APP_NAME = "kinjar-api"
  LOG_LEVEL = "INFO"
  PRESIGN_EXPIRES_SECONDS = "60"
  PRESIGN_MAX_MB = "50"
  PRESIGN_PREFIX = "t/"
  REQUIRE_TENANT = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    method = "GET"
    path = "/health"
    protocol = "http"
    grace_period = "30s"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
# ...your existing fly.toml...

[[mounts]]
  source = "data"        # the volume NAME from `fly volumes list`
  destination = "/data"  # typical mount path; use the actual one if you set it differently
