app = "kinjar-api"
primary_region = "iad"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false      # <— turn off suspend
  auto_start_machines = true
  min_machines_running = 1        # <— keep at least one up
  processes = ["app"]

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "30s"
    method = "get"
    path = "/health"
    protocol = "http"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "data"
  destination = "/app/data"
