name: Deploy kinjar-api to Fly.io

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP: kinjar-api
  PRIMARY_REGION: atl   # must match fly.toml primary_region

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Preflight (verify files and mounts)
        run: |
          set -euo pipefail
          test -f ./fly.toml || { echo "fly.toml not found at repo root"; exit 1; }
          test -f ./Dockerfile || { echo "Dockerfile not found at repo root"; exit 1; }
          echo "=== fly.toml (first 120 lines) ==="
          nl -ba ./fly.toml | sed -n '1,120p'
          echo "=== Verify [mounts] -> /data ==="
          grep -n '^\[mounts\]' ./fly.toml
          grep -n 'source *= *"data"' ./fly.toml
          grep -n 'destination *= *"/data"' ./fly.toml

      - name: Ensure volume exists
        run: |
          set -euo pipefail
          if fly volumes list -a "$FLY_APP" | awk '{print $2}' | grep -qx data; then
            echo "Volume 'data' already exists."
          else
            echo "Creating volume 'data' in region ${PRIMARY_REGION}..."
            fly volumes create data \
              -a "$FLY_APP" \
              -r "$PRIMARY_REGION" \
              --size 1
          fi
          echo "Current volumes:"
          fly volumes list -a "$FLY_APP"

      - name: Deploy (remote build)
        run: |
          set -euo pipefail
          fly deploy \
            -a "$FLY_APP" \
            --config ./fly.toml \
            --dockerfile ./Dockerfile \
            --remote-only \
            --now

      - name: Post-deploy sanity
        run: |
          set -euo pipefail
          fly status -a "$FLY_APP"
          fly machines list -a "$FLY_APP"
          fly volumes list -a "$FLY_APP"
