app = "kinjar-api"
primary_region = "atl"

[env]
  PORT = "8080"
  DATA_DIR = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  min_machines_running = 1
  auto_start_machines = true
  auto_stop_machines = false

  [[http_service.checks]]
    method = "get"
    path = "/health"
    interval = "10s"
    timeout = "2s"
    grace_period = "30s"

[mounts]
  source = "data"
  destination = "/data"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
