app = "kinjar-api"
primary_region = "atl"

[env]
  PORT = "8080"
  DATA_DIR = "/data"   # only needed if you mount the volume (we will)

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"

[mounts]
  source = "data"
  destination = "/data"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
