# fly.toml app configuration file generated for kinjar-api on 2025-08-17T21:52:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kinjar-api'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "30s"
    method = "get"
    path = "/health"
    protocol = "http"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

  memory_mb = 512

  source = "data"
  destination = "/app/data"

