name: Deploy to Fly
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Ensure volume exists (idempotent)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP: kinjar-api
          VOLUME_NAME: data
          REGION: atl
        run: |
          set -euo pipefail
          if flyctl volumes list --app "$FLY_APP" | awk '{print $1, $3}' | grep -q "^$VOLUME_NAME $REGION$"; then
            echo "Volume $VOLUME_NAME in $REGION already exists."
          else
            echo "Creating volume $VOLUME_NAME in $REGION..."
            flyctl volumes create "$VOLUME_NAME" --region "$REGION" --size 3 --app "$FLY_APP" --yes
          fi

      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --app kinjar-api --remote-only
