name: Deploy kinjar-api to Fly.io

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP: kinjar-api
  MACHINE_ID: 2867643a606e08      # update if your machine ID changes
  WORKDIR: backend                 # folder that contains fly.toml (change if needed)
  EXISTING_IMAGE: ""               # set to an image tag to skip building (optional)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Sanity check files
        run: |
          set -euo pipefail
          cd "$WORKDIR"
          test -f fly.toml || { echo "fly.toml not found in $PWD"; exit 1; }
          if [[ -z "$EXISTING_IMAGE" && ! -f Dockerfile ]]; then
            echo "Dockerfile not found and no EXISTING_IMAGE provided."
            exit 1
          fi

      - name: Deploy (update existing machine only)
        run: |
          set -euo pipefail
          cd "$WORKDIR"
          if [[ -n "$EXISTING_IMAGE" ]]; then
            echo "Deploying existing image: $EXISTING_IMAGE"
            fly deploy -a "$FLY_APP" \
              --image "$EXISTING_IMAGE" \
              --only-machines "$MACHINE_ID" \
              --update-only \
              --now
          else
            echo "Building from Dockerfile and deploying…"
            fly deploy -a "$FLY_APP" \
              --only-machines "$MACHINE_ID" \
              --update-only \
              --now
          fi

      - name: Post-deploy sanity
        run: |
          set -euo pipefail
          fly status -a "$FLY_APP"
          fly machines list -a "$FLY_APP"
