name: Deploy kinjar-api to Fly.io

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP: kinjar-api
  PRIMARY_REGION: atl

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install flyctl
        shell: bash
        run: |
          set -euo pipefail
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> "$GITHUB_PATH"
          export PATH="$HOME/.fly/bin:$PATH"
          fly version

      - name: Preflight (verify files and mounts)
        shell: bash
        run: |
          set -euo pipefail
          test -f ./fly.toml
          test -f ./Dockerfile
          # MUST already have one good volume; we DO NOT create in CI anymore
          echo "Existing volumes:"
          export PATH="$HOME/.fly/bin:$PATH"
          fly volumes list -a "$FLY_APP"

      # IMPORTANT: in-place update so Fly doesn't create a new machine/volume
      - name: Deploy (in-place, remote build)
        shell: bash
        run: |
          set -euo pipefail
          export PATH="$HOME/.fly/bin:$PATH"
          fly deploy \
            -a "$FLY_APP" \
            --config ./fly.toml \
            --dockerfile ./Dockerfile \
            --remote-only \
            --strategy immediate \
            --now

      - name: Post-deploy sanity
        shell: bash
        run: |
          set -euo pipefail
          export PATH="$HOME/.fly/bin:$PATH"
          fly status -a "$FLY_APP"
          fly machines list -a "$FLY_APP"
          fly volumes list -a "$FLY_APP"
