name: Deploy kinjar-api to Fly.io

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  FLY_APP: kinjar-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Preflight
        run: |
          test -f ./fly.toml
          test -f ./Dockerfile
          flyctl status -a "$FLY_APP" || true
          flyctl volumes list -a "$FLY_APP" || true
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy (remote build)
        run: |
          flyctl deploy \
            --app "$FLY_APP" \
            --config ./fly.toml \
            --dockerfile ./Dockerfile \
            --remote-only \
            --strategy immediate \
            --now
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Post-deploy sanity
        run: |
          flyctl status -a "$FLY_APP"
          flyctl machines list -a "$FLY_APP"
          flyctl volumes list -a "$FLY_APP"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
